---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{- include "identifier" . }}-sa"
  namespace: {{ .Values.application.stage }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.application.account }}:role/eks-irsa-{{- include "identifier" . }}-role
automountServiceAccountToken: false
