---
apiVersion: v1
kind: Service
metadata:
  name: "{{- include "identifier" . }}-service"
  namespace: {{ .Values.application.stage }}
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: {{ .Values.service.type }}
