---
apiVersion: v1
kind: Service
metadata:
  name: "{{- include "identifier" . }}-service"
  namespace: {{ .Values.application.stage }}
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  type: {{ .Values.service.type }}