---
apiVersion: javaland.cloud.platform.api/v1alpha1
kind: ApiGateway
metadata:
  name: "{{- include "identifier" . }}"
  namespace: {{ .Values.application.stage }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  service:
    name:  {{ .Values.application.name }}
    stage: {{ .Values.application.stage }}
  parameters:
    region: {{ .Values.application.region }}
    protocol: HTTP
    domainName: {{ .Values.application.domain }}
