---
apiVersion: we.are.developers.demo/v1alpha1
kind: XAPIGateway
metadata:
  name: "{{- include "identifier" . }}-apigateway"
spec:
  service:
    name: {{ .Values.application.name }}
    region: {{ .Values.application.region }}
    cluster: {{ .Values.application.cluster }}
  properties:
    protocol: HTTP
  compositionSelector:
    matchLabels:
      provider: aws
