---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{- include "identifier" . }}-sa"
  namespace: {{ .Values.application.stage }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::518283773752:role/{{ .Values.application.name }}-iam-role-nosql-database
automountServiceAccountToken: false
