---
apiVersion: v1
kind: Service
metadata:
  name: "{{- include "identifier" . }}-service"
  namespace: {{ .Values.application.stage }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  type: {{ .Values.service.type }}