application:
  name:   javaland-demo
  stage:  dev
  region: eu-west-1
  account: '518283773752'
  replicas: 1
  cluster: dev-cluster

image:
  repository: 518283773752.dkr.ecr.eu-west-1.amazonaws.com/aws-community-day-dach-2022
  pullPolicy: Always
  tag: 0.0.1

service:
  type: NodePort
  port: 80

autoscaling:
  enabled: false

irsa:
  enable: true