application:
  name: javaland-demo
  stage: dev
  region: eu-west-1
  domain: javaland.ntt-tech-demo.com
  cluster: dev-cluster
  replicas: 1

image:
  repository: 518283773752.dkr.ecr.eu-west-1.amazonaws.com/javaland
  pullPolicy: Always
  tag: latest

service:
  type: NodePort
  port: 80

autoscaling:
  enabled: false

irsa:
  enable: true
  account: '518283773752'
  oidcProvider: oidc.eks.eu-west-1.amazonaws.com/id/4AD430FA3CA1E40C32EF47C7C5C41E9B
