application:
  name:     jet-demo
  stage:    dev
  region: eu-central-1
  replicas: 1
  cluster:  dev-cluster

image:
  #repository: gcr.io/google_containers/echoserver
  repository: 518283773752.dkr.ecr.eu-central-1.amazonaws.com/jet-demo-frontend
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.1.0

service:
  type: NodePort
  port: 80
