application:
  name:     jet-demo
  stage:    dev
  region: eu-central-1
  replicas: 1
  cluster:  dev-cluster

image:
  repository: 518283773752.dkr.ecr.eu-central-1.amazonaws.com/jet-demo-frontend
  pullPolicy: Always
  tag: 0.5.0

service:
  type: NodePort
  port: 80
