application:
  name: wad-demo
  stage: dev
  region: eu-west-2
  domain: wad.ntt-tech-demo.com
  cluster: test-eks-cluster
  replicas: 2

image:
  repository: 518283773752.dkr.ecr.eu-west-2.amazonaws.com/we.are.developers.demo
  pullPolicy: Always
  tag: 1.0.1

service:
  type: NodePort
  port: 9090

autoscaling:
  enabled: false

irsa:
  enabled: false
